#!/bin/bash

# Programador: José Claudio Pereira <Nyex>
# TempFreezer - Ver: 2.0.0
# Controlador de inicialização do TempFreezer

#Variaveis do script
contador="/etc/.TempFreezer/Contador.txt"
configs="/etc/.TempFreezer/Configs.txt"

# Função que liga o script no boot do sistema
start(){
  sed -i 's/'"INICIALIZAO_NO_BOOT=nao"'/'"INICIALIZAO_NO_BOOT=sim"'/g' $configs
}

# Função que desliga o script no boot do sistema
stop(){
  sed -i 's/'"INICIALIZAO_NO_BOOT=sim"'/'"INICIALIZAO_NO_BOOT=nao"'/g' $configs
}

reset(){
	linha=$(head $contador)
  sed -i 's/'"$linha"'/'0'/g' $contador
  echo "   * Contador resetado com sucesso."
}

case "$1" in

  start)
    start
  ;;

  stop)
    stop
  ;;

  reset)
    reset
  ;;

  *)
    echo $"Use: $0 {start|stop|reset}"
    echo "    start - Adicionar serviço no boot do sistema"
    echo "    stop  - Remover serviço no boot do sistema"
    echo "    reset - Resetar o contador do script"
    exit 1
esac
